export const initialButtonComponentStyles = [
  {
    colorhex: "#FF0000",
    backgroundcolor: "#FFFFFF",
    fontsize: "12px",
    font: "sans-serif",
    fontweight: "normal",
    fontstyle: "normal",
    fontfamily: "ABeeZee",
    hovercolor: "#0000FF",
    mdwidth: "100px",
  },
  {
    colorhex: "#FFFFFF",
    backgroundcolor: "#FF0000",
    fontsize: "12px",
    font: "sans-serif",
    fontweight: "bold",
    fontstyle: "normal",
    fontfamily: "ABeeZee",
    hovercolor: "#0000FF",
    mdwidth: "200px",
  },
  {
    colorhex: "#FFFFFF",
    backgroundcolor: "#FFFF00",
    fontsize: "12px",
    font: "sans-serif",
    fontweight: "normal",
    fontstyle: "italic",
    fontfamily: "ABeeZee",
    hovercolor: "#0000FF",
    mdwidth: "300px",
  },
];
